export interface Theme {
  name: string;
  category: string;
  primary: string;
  primarySolid: string;
  primaryHover: string;
  secondary: string;
  accent: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  bg: string;
  surface: string;
  border: string;
  hero: string;
  glow: string;
  isDark: boolean;
  therapeutic?: boolean;
  accessibility?: boolean;
}

export const themes: Record<string, Theme> = {
  // === RESEARCH PALETTES ===
  coastalBreeze: {
    name: "Coastal Breeze",
    category: "Research Palettes",
    primary: "from-teal-600 to-cyan-600",
    primarySolid: "bg-teal-600",
    primaryHover: "hover:bg-cyan-600",
    secondary: "bg-amber-500",
    accent: "bg-slate-50",
    text: "text-slate-900",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-white",
    surface: "bg-slate-50/80",
    border: "border-slate-300",
    hero: "bg-gradient-to-br from-slate-50 via-white to-cyan-50",
    glow: "shadow-teal-500/20",
    isDark: false,
  },
  coastalGlow: {
    name: "Coastal Glow",
    category: "Research Palettes",
    primary: "from-teal-600 to-cyan-600",
    primarySolid: "bg-teal-600",
    primaryHover: "hover:bg-cyan-600",
    secondary: "bg-amber-500",
    accent: "bg-slate-50",
    text: "text-slate-900",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-slate-50",
    surface: "bg-white/95",
    border: "border-slate-200",
    hero: "bg-gradient-to-br from-slate-50 via-white to-cyan-50",
    glow: "shadow-teal-500/20",
    isDark: false,
  },
  earthySerenity: {
    name: "Earthy Serenity",
    category: "Research Palettes",
    primary: "from-green-400 to-emerald-500",
    primarySolid: "bg-green-500",
    primaryHover: "hover:bg-emerald-500",
    secondary: "bg-rose-300",
    accent: "bg-orange-50",
    text: "text-slate-800",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-orange-50",
    surface: "bg-white/90",
    border: "border-orange-200",
    hero: "bg-gradient-to-br from-orange-50 via-green-50 to-rose-50",
    glow: "shadow-green-400/15",
    isDark: false,
  },
  neonTide: {
    name: "Neon Tide",
    category: "Research Palettes",
    primary: "from-teal-400 to-cyan-400",
    primarySolid: "bg-teal-400",
    primaryHover: "hover:bg-cyan-400",
    secondary: "bg-amber-400",
    accent: "bg-slate-800",
    text: "text-slate-100",
    textSecondary: "text-slate-300",
    textMuted: "text-slate-400",
    bg: "bg-slate-900",
    surface: "bg-slate-800/80",
    border: "border-slate-600",
    hero: "bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900/20",
    glow: "shadow-cyan-400/25",
    isDark: true,
  },
  cyberMint: {
    name: "Cyber Mint",
    category: "Research Palettes",
    primary: "from-teal-300 to-emerald-300",
    primarySolid: "bg-teal-300",
    primaryHover: "hover:bg-emerald-300",
    secondary: "bg-yellow-300",
    accent: "bg-slate-800",
    text: "text-slate-100",
    textSecondary: "text-slate-300",
    textMuted: "text-slate-400",
    bg: "bg-slate-900",
    surface: "bg-slate-800/80",
    border: "border-slate-600",
    hero: "bg-gradient-to-br from-slate-900 via-slate-800 to-teal-900/20",
    glow: "shadow-teal-400/25",
    isDark: true,
  },
  midnightPulse: {
    name: "Midnight Pulse",
    category: "Research Palettes",
    primary: "from-blue-400 to-cyan-400",
    primarySolid: "bg-blue-400",
    primaryHover: "hover:bg-cyan-400",
    secondary: "bg-red-500",
    accent: "bg-slate-700",
    text: "text-slate-100",
    textSecondary: "text-slate-300",
    textMuted: "text-slate-400",
    bg: "bg-slate-900",
    surface: "bg-slate-700/80",
    border: "border-slate-600",
    hero: "bg-gradient-to-br from-slate-900 via-slate-800 to-blue-900/20",
    glow: "shadow-blue-400/25",
    isDark: true,
  },

  // === ORIGINAL THEMES (fully restored) ===
  coastalBreezeOriginal: {
    name: "Coastal Breeze (Original)",
    category: "Original",
    primary: "from-cyan-700 to-teal-800",
    primarySolid: "bg-cyan-700",
    primaryHover: "hover:bg-teal-800",
    secondary: "bg-amber-500",
    accent: "bg-cyan-50/80",
    text: "text-slate-900",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-slate-50",
    surface: "bg-white/80",
    border: "border-slate-300",
    hero: "bg-gradient-to-br from-cyan-50 via-white to-slate-50",
    glow: "shadow-cyan-500/20",
    isDark: false,
  },
  anthropicLight: {
    name: "Anthropic Light",
    category: "Original",
    primary: "from-orange-600 to-red-600",
    primarySolid: "bg-orange-600",
    primaryHover: "hover:bg-red-600",
    secondary: "bg-gray-600",
    accent: "bg-orange-50",
    text: "text-gray-900",
    textSecondary: "text-gray-800",
    textMuted: "text-gray-700",
    bg: "bg-white",
    surface: "bg-gray-50",
    border: "border-gray-400",
    hero: "bg-gradient-to-br from-gray-50 via-white to-orange-50/20",
    glow: "shadow-orange-600/15",
    isDark: false,
  },
  anthropicDark: {
    name: "Anthropic Dark",
    category: "Original",
    primary: "from-orange-400 to-red-400",
    primarySolid: "bg-orange-500",
    primaryHover: "hover:bg-red-500",
    secondary: "bg-gray-600",
    accent: "bg-gray-800",
    text: "text-gray-100",
    textSecondary: "text-gray-300",
    textMuted: "text-gray-400",
    bg: "bg-gray-900",
    surface: "bg-gray-800",
    border: "border-gray-700",
    hero: "bg-gradient-to-br from-gray-900 via-gray-800 to-orange-900/20",
    glow: "shadow-orange-500/25",
    isDark: true,
  },
  neonTideOriginal: {
    name: "Neon Tide (Original)",
    category: "Original",
    primary: "from-cyan-400 to-teal-500",
    primarySolid: "bg-cyan-400",
    primaryHover: "hover:bg-teal-500",
    secondary: "bg-orange-400",
    accent: "bg-slate-800/50",
    text: "text-slate-100",
    textSecondary: "text-slate-300",
    textMuted: "text-slate-400",
    bg: "bg-slate-900",
    surface: "bg-slate-800/50",
    border: "border-slate-600",
    hero: "bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900/20",
    glow: "shadow-cyan-400/25",
    isDark: true,
  },

  // === THERAPY/CRISIS THEMES ===
  calmUnity: {
    name: "Calm Unity",
    category: "Therapy/Crisis",
    primary: "from-blue-500 to-teal-500",
    primarySolid: "bg-blue-500",
    primaryHover: "hover:bg-teal-500",
    secondary: "bg-emerald-400",
    accent: "bg-blue-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-slate-50",
    surface: "bg-white/95",
    border: "border-blue-200",
    hero: "bg-gradient-to-br from-blue-50 via-teal-50 to-emerald-50",
    glow: "shadow-blue-300/15",
    isDark: false,
    therapeutic: true,
  },
  healingHorizon: {
    name: "Healing Horizon",
    category: "Therapy/Crisis",
    primary: "from-blue-500 to-teal-500",
    primarySolid: "bg-blue-500",
    primaryHover: "hover:bg-teal-500",
    secondary: "bg-rose-400",
    accent: "bg-blue-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-gradient-to-br from-blue-50 to-teal-50",
    surface: "bg-white/90",
    border: "border-blue-200",
    hero: "bg-gradient-to-br from-blue-50 via-teal-50 to-rose-50",
    glow: "shadow-blue-400/20",
    isDark: false,
    therapeutic: true,
  },
  tranquilTrust: {
    name: "Tranquil Trust",
    category: "Therapy/Crisis",
    primary: "from-slate-500 to-blue-500",
    primarySolid: "bg-slate-500",
    primaryHover: "hover:bg-blue-500",
    secondary: "bg-teal-400",
    accent: "bg-orange-50/80",
    text: "text-slate-900",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-orange-50",
    surface: "bg-white/85",
    border: "border-slate-300",
    hero: "bg-gradient-to-br from-orange-50 via-blue-50 to-slate-50",
    glow: "shadow-slate-400/15",
    isDark: false,
    therapeutic: true,
  },
  warmEmpathy: {
    name: "Warm Empathy",
    category: "Therapy/Crisis",
    primary: "from-rose-500 to-pink-500",
    primarySolid: "bg-rose-500",
    primaryHover: "hover:bg-pink-500",
    secondary: "bg-yellow-400",
    accent: "bg-rose-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-rose-50",
    surface: "bg-white/90",
    border: "border-rose-200",
    hero: "bg-gradient-to-br from-rose-50 via-pink-50 to-yellow-50",
    glow: "shadow-rose-400/20",
    isDark: false,
    therapeutic: true,
  },
  safeguardSerene: {
    name: "Safeguard Serene",
    category: "Therapy/Crisis",
    primary: "from-emerald-500 to-teal-500",
    primarySolid: "bg-emerald-500",
    primaryHover: "hover:bg-teal-500",
    secondary: "bg-indigo-400",
    accent: "bg-emerald-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-emerald-50",
    surface: "bg-white/90",
    border: "border-emerald-200",
    hero: "bg-gradient-to-br from-emerald-50 via-teal-50 to-indigo-50",
    glow: "shadow-emerald-400/20",
    isDark: false,
    therapeutic: true,
  },
  crisisCompanion: {
    name: "Crisis Companion",
    category: "Therapy/Crisis",
    primary: "from-purple-500 to-indigo-500",
    primarySolid: "bg-purple-500",
    primaryHover: "hover:bg-indigo-500",
    secondary: "bg-teal-400",
    accent: "bg-purple-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-purple-50",
    surface: "bg-white/90",
    border: "border-purple-200",
    hero: "bg-gradient-to-br from-purple-50 via-indigo-50 to-teal-50",
    glow: "shadow-purple-400/20",
    isDark: false,
    therapeutic: true,
  },

  // === ACCESSIBILITY THEMES ===
  accessibilityHigh: {
    name: "High Contrast",
    category: "Accessibility",
    primary: "from-black to-gray-900",
    primarySolid: "bg-black",
    primaryHover: "hover:bg-gray-900",
    secondary: "bg-yellow-400",
    accent: "bg-white",
    text: "text-black",
    textSecondary: "text-gray-900",
    textMuted: "text-gray-800",
    bg: "bg-white",
    surface: "bg-gray-50",
    border: "border-black",
    hero: "bg-white",
    glow: "shadow-black/50",
    isDark: false,
    accessibility: true,
  },
  deuteranopia: {
    name: "Deuteranopia Safe",
    category: "Accessibility",
    primary: "from-blue-700 to-purple-700",
    primarySolid: "bg-blue-700",
    primaryHover: "hover:bg-purple-700",
    secondary: "bg-yellow-500",
    accent: "bg-blue-50",
    text: "text-slate-900",
    textSecondary: "text-slate-800",
    textMuted: "text-slate-700",
    bg: "bg-white",
    surface: "bg-blue-50/50",
    border: "border-slate-400",
    hero: "bg-gradient-to-br from-blue-50 via-white to-purple-50/20",
    glow: "shadow-blue-600/20",
    isDark: false,
    accessibility: true,
  },
};
