/**
 * Theme interface defining the structure for all color palettes used in the platform.
 * Supports both light and dark modes with specialized therapeutic and accessibility options.
 */
export interface Theme {
  name: string;
  category: string;
  primary: string;
  primarySolid: string;
  primaryHover: string;
  secondary: string;
  accent: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  bg: string;
  surface: string;
  border: string;
  hero: string;
  glow: string;
  isDark: boolean;
  therapeutic?: boolean;
  accessibility?: boolean;
}

/**
 * Collection of streamlined themes for the platform.
 * Reduced from 31 to 12 core themes while preserving all design variety.
 */
export const themes: Record<string, Theme> = {
  // === LIGHT THEMES ===
  coastalBreeze: {
    name: "Coastal Breeze",
    category: "Light",
    primary: "from-teal-700 to-emerald-700",
    primarySolid: "bg-teal-700",
    primaryHover: "hover:bg-emerald-700",
    secondary: "bg-orange-400",
    accent: "bg-slate-50",
    text: "text-slate-900",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-white",
    surface: "bg-slate-50/80",
    border: "border-slate-300",
    hero: "bg-gradient-to-br from-slate-50 via-white to-teal-50",
    glow: "shadow-teal-500/20",
    isDark: false,
  },
  coastalGlow: {
    name: "Coastal Glow",
    category: "Light",
    primary: "from-emerald-600 to-teal-600",
    primarySolid: "bg-emerald-600",
    primaryHover: "hover:bg-teal-600",
    secondary: "bg-teal-400",
    accent: "bg-emerald-50",
    text: "text-slate-900",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-green-50",
    surface: "bg-white/90",
    border: "border-emerald-200",
    hero: "bg-gradient-to-br from-green-50 via-emerald-50 to-teal-50",
    glow: "shadow-emerald-500/20",
    isDark: false,
  },
  earthySerenity: {
    name: "Earthy Serenity",
    category: "Light",
    primary: "from-emerald-600 to-teal-600",
    primarySolid: "bg-emerald-600",
    primaryHover: "hover:bg-teal-600",
    secondary: "bg-orange-400",
    accent: "bg-orange-50",
    text: "text-slate-800",
    textSecondary: "text-slate-700",
    textMuted: "text-slate-600",
    bg: "bg-orange-50",
    surface: "bg-white/90",
    border: "border-orange-200",
    hero: "bg-gradient-to-br from-orange-50 via-emerald-50 to-teal-50",
    glow: "shadow-emerald-400/15",
    isDark: false,
  },
  anthropicLight: {
    name: "Anthropic Light",
    category: "Light",
    primary: "from-orange-600 to-red-600",
    primarySolid: "bg-orange-600",
    primaryHover: "hover:bg-red-600",
    secondary: "bg-gray-600",
    accent: "bg-orange-50",
    text: "text-gray-900",
    textSecondary: "text-gray-800",
    textMuted: "text-gray-700",
    bg: "bg-white",
    surface: "bg-gray-50",
    border: "border-gray-400",
    hero: "bg-gradient-to-br from-gray-50 via-white to-orange-50/20",
    glow: "shadow-orange-600/15",
    isDark: false,
  },

  // === DARK THEMES ===
  neonTide: {
    name: "Neon Tide",
    category: "Dark",
    primary: "from-cyan-400 to-teal-400",
    primarySolid: "bg-cyan-400",
    primaryHover: "hover:bg-teal-400",
    secondary: "bg-orange-500",
    accent: "bg-slate-800",
    text: "text-slate-100",
    textSecondary: "text-slate-300",
    textMuted: "text-slate-400",
    bg: "bg-slate-900",
    surface: "bg-slate-800/80",
    border: "border-slate-600",
    hero: "bg-gradient-to-br from-slate-900 via-slate-800 to-cyan-900/20",
    glow: "shadow-cyan-400/25",
    isDark: true,
  },
  cyberMint: {
    name: "Cyber Mint",
    category: "Dark",
    primary: "from-emerald-400 to-green-400",
    primarySolid: "bg-emerald-400",
    primaryHover: "hover:bg-green-400",
    secondary: "bg-lime-400",
    accent: "bg-slate-800",
    text: "text-slate-100",
    textSecondary: "text-slate-300",
    textMuted: "text-slate-400",
    bg: "bg-slate-900",
    surface: "bg-slate-800/80",
    border: "border-slate-600",
    hero: "bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-900/20",
    glow: "shadow-emerald-400/25",
    isDark: true,
  },
  midnightPulse: {
    name: "Midnight Pulse",
    category: "Dark",
    primary: "from-blue-400 to-cyan-400",
    primarySolid: "bg-blue-400",
    primaryHover: "hover:bg-cyan-400",
    secondary: "bg-blue-300",
    accent: "bg-slate-800",
    text: "text-slate-100",
    textSecondary: "text-slate-300",
    textMuted: "text-slate-400",
    bg: "bg-slate-900",
    surface: "bg-slate-800/80",
    border: "border-slate-600",
    hero: "bg-gradient-to-br from-slate-900 via-slate-800 to-blue-900/20",
    glow: "shadow-blue-400/25",
    isDark: true,
  },
  anthropicDark: {
    name: "Anthropic Dark",
    category: "Dark",
    primary: "from-orange-400 to-red-400",
    primarySolid: "bg-orange-500",
    primaryHover: "hover:bg-red-500",
    secondary: "bg-gray-600",
    accent: "bg-gray-800",
    text: "text-gray-100",
    textSecondary: "text-gray-300",
    textMuted: "text-gray-400",
    bg: "bg-gray-900",
    surface: "bg-gray-800",
    border: "border-gray-700",
    hero: "bg-gradient-to-br from-gray-900 via-gray-800 to-orange-900/20",
    glow: "shadow-orange-500/25",
    isDark: true,
  },

  // === THERAPEUTIC THEMES ===
  calmUnity: {
    name: "Calm Unity",
    category: "Therapeutic",
    primary: "from-blue-500 to-teal-500",
    primarySolid: "bg-blue-500",
    primaryHover: "hover:bg-teal-500",
    secondary: "bg-emerald-400",
    accent: "bg-blue-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-slate-50",
    surface: "bg-white/95",
    border: "border-blue-200",
    hero: "bg-gradient-to-br from-blue-50 via-teal-50 to-emerald-50",
    glow: "shadow-blue-300/15",
    isDark: false,
    therapeutic: true,
  },
  warmEmpathy: {
    name: "Warm Empathy",
    category: "Therapeutic",
    primary: "from-rose-500 to-pink-500",
    primarySolid: "bg-rose-500",
    primaryHover: "hover:bg-pink-500",
    secondary: "bg-yellow-400",
    accent: "bg-rose-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-rose-50",
    surface: "bg-white/90",
    border: "border-rose-200",
    hero: "bg-gradient-to-br from-rose-50 via-pink-50 to-yellow-50",
    glow: "shadow-rose-400/20",
    isDark: false,
    therapeutic: true,
  },
  safeguardSerene: {
    name: "Safeguard Serene",
    category: "Therapeutic",
    primary: "from-emerald-500 to-teal-500",
    primarySolid: "bg-emerald-500",
    primaryHover: "hover:bg-teal-500",
    secondary: "bg-indigo-400",
    accent: "bg-emerald-50/90",
    text: "text-slate-800",
    textSecondary: "text-slate-600",
    textMuted: "text-slate-500",
    bg: "bg-emerald-50",
    surface: "bg-white/90",
    border: "border-emerald-200",
    hero: "bg-gradient-to-br from-emerald-50 via-teal-50 to-indigo-50",
    glow: "shadow-emerald-400/20",
    isDark: false,
    therapeutic: true,
  },

  // === ACCESSIBILITY THEMES ===
  accessibilityHigh: {
    name: "High Contrast",
    category: "Accessibility",
    primary: "from-black to-gray-900",
    primarySolid: "bg-black",
    primaryHover: "hover:bg-gray-900",
    secondary: "bg-yellow-400",
    accent: "bg-white",
    text: "text-black",
    textSecondary: "text-gray-900",
    textMuted: "text-gray-800",
    bg: "bg-white",
    surface: "bg-gray-50",
    border: "border-black",
    hero: "bg-white",
    glow: "shadow-black/50",
    isDark: false,
    accessibility: true,
  },
  deuteranopia: {
    name: "Deuteranopia Safe",
    category: "Accessibility",
    primary: "from-blue-700 to-purple-700",
    primarySolid: "bg-blue-700",
    primaryHover: "hover:bg-purple-700",
    secondary: "bg-yellow-500",
    accent: "bg-blue-50",
    text: "text-slate-900",
    textSecondary: "text-slate-800",
    textMuted: "text-slate-700",
    bg: "bg-white",
    surface: "bg-blue-50/50",
    border: "border-slate-400",
    hero: "bg-gradient-to-br from-blue-50 via-white to-purple-50/20",
    glow: "shadow-blue-600/20",
    isDark: false,
    accessibility: true,
  },
};
